name: cd

on: 
  push: 
    branches:
      - main
  
jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Crot dalem
        uses: appleboy/ssh-action@master
        # uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # password: ${{ secrets.SSH_PASSWORD }}
          # host: ${{ secrets.SSH_HOST }}
          # user: ${{ secrets.SSH_USERNAME }}
          # pass: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /home/pdau
            ls -l

